# intrinsics
K: [[930,0,640],[0,930,360],[0,0,1]]
dist: [0,0,0,0,0]
# extrinsics: 相机在 base 下的位姿（临时占位，后续手眼标定再改）
T_base_cam: [[1,0,0,0.15],[0,1,0,0.0],[0,0,1,0.90],[0,0,0,1]]
source: "0"
width: 1280
height: 720
