# Frame relations
# 坐标系关系（示例）
T_base_cam:  # 4x4 row-major
  - [1.0, 0.0, 0.0, 0.50]
  - [0.0, 1.0, 0.0, 0.00]
  - [0.0, 0.0, 1.0, 0.60]
  - [0.0, 0.0, 0.0, 1.0]

T_base_place:  # 放置位姿（示例）
  - [1.0, 0.0, 0.0, 0.80]
  - [0.0, 1.0, 0.0, 0.00]
  - [0.0, 0.0, 1.0, 0.30]
  - [0.0, 0.0, 0.0, 1.0]
